using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.IO;
using System.Collections;

namespace Cpp2Lua
{
    class Writer
    {
        public void WriteLuaDefineFile(ArrayList list, string file)
        {
            StringBuilder sb = new StringBuilder();
            
            sb.Append("----------this file is generated by tool, don't try to modify it...").Append(Environment.NewLine).Append(Environment.NewLine);
            for (int i = 0; i < list.Count; i ++)
            {
                Struct st = list[i] as Struct;
                if (st != null && st.included == false)
                {
                    sb.Append(st.GetStructDefineString());                          
                }
            }            
                        
            byte[] myByte = System.Text.Encoding.UTF8.GetBytes(sb.ToString());  //转换为字节
            using (FileStream fsWrite = new FileStream(file, FileMode.Create))
            {
                fsWrite.Write(myByte, 0, myByte.Length);
            };
        }                      
    }
}
